"""Create a baseline migrations

Revision ID: 0e4a29511c88
Revises: 
Create Date: 2025-01-11 22:11:33.184469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0e4a29511c88'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rebate_programs',
                    sa.Column('id', sa.Integer(), autoincrement=True,
                              nullable=False),
                    sa.Column('program_name', sa.String(), nullable=False),
                    sa.Column('rebate_percentage', sa.Float(), nullable=False),
                    sa.Column('start_date', sa.DateTime(), nullable=False),
                    sa.Column('end_date', sa.DateTime(), nullable=False),
                    sa.Column('eligibility_criteria', sa.Text(), nullable=True),
                    sa.Column('last_update_time', sa.DateTime(),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('program_name')
                    )
    op.create_table('transactions',
                    sa.Column('id', sa.Integer(), autoincrement=True,
                              nullable=False),
                    sa.Column('amount', sa.Float(), nullable=False),
                    sa.Column('transaction_date', sa.DateTime(),
                              nullable=False),
                    sa.Column('rebate_program_id', sa.Integer(),
                              nullable=False),
                    sa.Column('last_update_time', sa.DateTime(),
                              nullable=False),
                    sa.ForeignKeyConstraint(['rebate_program_id'],
                                            ['rebate_programs.id'],
                                            ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('rebate_claims',
                    sa.Column('id', sa.Integer(), autoincrement=True,
                              nullable=False),
                    sa.Column('transaction_id', sa.Integer(), nullable=False),
                    sa.Column('claim_amount', sa.Float(), nullable=False),
                    sa.Column('claim_status', sa.String(), nullable=True),
                    sa.Column('claim_date', sa.DateTime(), nullable=False),
                    sa.Column('last_update_time', sa.DateTime(),
                              nullable=False),
                    sa.ForeignKeyConstraint(['transaction_id'],
                                            ['transactions.id'],
                                            ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rebate_claims')
    op.drop_table('transactions')
    op.drop_table('rebate_programs')
    # ### end Alembic commands ###
